baseurl = "https://www.vle-project.org/"
languageCode = "en-us"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
hasCJKLanguage = true
title = "Virtual Laboratory Environment"
MetaDataFormat = "toml"
theme = "hugo-theme-techdoc"
canonifyurls = true
paginate = 10
author = "INRA"
copyright = "&copy; 2018 INRA"
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "monokai"
pygmentsUseClasses = true
PygmentsCodeFences = true

[params]
 description = "A Modeling & Simulation Environment"
 github_repository = "https://github.com/vle-forge/"
 github_doc_repository = "https://github.com/vle-forge/vle-project.org"
 version = "2.0.2"
 brand = "VLE"
 highlightjs = "androidstudio"
 dateFormat = "02 Jan 2006, 15:04"
 menu_exclusion = ["archives", "post", "posts"]

 [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
 [[menu.main]]
  name = "About"
  pre = "<i class='fa fa-user fa-fw'></i>"
  weight = 2
  identifier = "about"
  url = "/about/"
 [[menu.main]]
  name = "Download"
  pre = "<i class='fa fa-download fa-fw'></i>"
  weight = 3
  identifier = "download"
  url = "/download/"
 [[menu.main]]
  name = "Documentation"
  pre = "<i class='fa fa-book fa-fw'></i>"
  weight = 4
  identifier = "documentation"
  url = "/documentation/"
 [[menu.main]]
  name = "Packages"
  pre = "<i class='fa fa-folder fa-fw'></i>"
  weight = 5
  identifier = "packages"
  url = "/packages/"
 [[menu.main]]
  name = "Tutorials"
  pre = "<i class='fa fa-check-square-o fa-fw'></i>"
  weight = 6
  identifier = "Tutorials"
  url = "/tutorials/"
 [[menu.main]]
  name = "Discussion"
  pre = "<i class='fa fa-phone fa-fw'></i>"
  weight = 7
  identifier = "Discussion"
  url = "/discussion/"

